# This workflow runs the JSON checker on each vendordep JSON file.

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-json-checker"
  run-json-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Get the ubuntu-base docker image
    #container: wpilib/ubuntu-base:18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history so we can use git diff

    - name: Install dependencies
      run: sudo pip3 install pyelftools pefile

    - name: Run check
      run: |
        # Determine the base commit
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          BASE_COMMIT=$(git merge-base HEAD ${{ github.base_ref }})
        else
          BASE_COMMIT=${{ github.event.before }}
        fi
        echo "Base commit: $BASE_COMMIT"

        # Get list of changed JSON files
        git diff --diff-filter=AM --name-only $BASE_COMMIT HEAD | grep '\.json$' > changed_json_files.txt

        # Run check.py on each changed JSON file
        if [ -s changed_json_files.txt ]; then
          xargs -a changed_json_files.txt ./check.py
        else
          echo "No JSON files changed"
        fi
